# Site settings
title: toby.wtf/is
email: toby@warmfusion.co.uk
description: >
  Through my work at Future PLC I get
  the chance to discover new and interesting technologies that others 
  may not have been exposed to. This site shares some of that experience
  by letting people ask Toby, WTF is...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://toby.wtf" # the base hostname & protocol for your site
twitter_username: warmfusion
github_username:  warmfusion

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: ops  # values [ ops, default ]

more_vert:
  option1:
    name: warmfusion.co.uk
    link: http://www.warmfusion.co.uk

permalink: is/:title

# Build settings
markdown: kramdown

gems:
  - jemoji